
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from Functions import Convert_PDF

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\xbsbu\Desktop\Workspace\Teste Interface grafica\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    791.0,
    360.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    145.0,
    58.0,
    image=image_image_2
)

canvas.create_text(
    353.0,
    32.0,
    anchor="nw",
    text="Bem vindo a plataforma Mazars",
    fill="#FFFFFF",
    font=("Inter", 48 * -1)
)

canvas.create_text(
    353.0,
    123.0,
    anchor="nw",
    text="Aqui podesmos realizar o tratamento de dados",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)
canvas.create_text(
    353.0,
    160.0,
    anchor="nw",
    text=" recebidos e agilizar os seus projetos.",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    791.0,
    444.0,
    image=image_image_3
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    145.0,
    176.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#F8F8F8",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=30.0,
    y=160.0,
    width=230.0,
    height=30.0
)

canvas.create_text(
    32.0,
    125.0,
    anchor="nw",
    text="Nome",
    fill="#A1A1A1",
    font=("Inter", 20 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    145.0,
    280.0,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#F8F8F8",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=30.0,
    y=265.0,
    width=230.0,
    height=30.0
)

canvas.create_text(
    32.0,
    231.0,
    anchor="nw",
    text="Diretório do arquivo",
    fill="#A1A1A1",
    font=("Inter", 20 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    145.0,
    383.0,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#F8F8F8",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=30.0,
    y=370.0,
    width=230.0,
    height=30.0
)

canvas.create_text(
    32.0,
    335.0,
    anchor="nw",
    text="Tipo de análise",
    fill="#A1A1A1",
    font=("Inter", 20 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: Convert_PDF.Convert("teste"),
    relief="flat"
)
button_1.place(
    x=20.0,
    y=438.0,
    width=250.0,
    height=60.0
)
window.resizable(False, False)
window.mainloop()
